package uk.co.ogauthority.pathfinder.analytics;

public enum AnalyticsEventCategory {

  SAVE_PROJECT_FORM,
  SAVE_PROJECT_FORM_COMPLETE_LATER,

  PROJECT_SUBMISSION,

  NEW_SUBSCRIBER,
  SUBSCRIBER_UNSUBSCRIBED,

  NO_CHANGE_UPDATE_SUBMITTED,

  UPDATE_REQUESTED,

  PROJECT_DRAFT_CANCELLED,

  SHOW_DIFFS_PROJECT,

  WORK_AREA_FILTERED

}