kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: drone-cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
        # We can only mount volume caches into the working directory, so all steps which use Gradle must have
        # the GRADLE_USER_HOME environment variable pointing here.
        - ./gradle_cache
        - ./sonar_cache

  - name: fetch-fds-submodule
    image: alpine/git:v2.26.2
    commands:
      # Drone cannot auth to a ssh based repo, so override to https to make use of .netrc
      - git config submodule.fivium-design-system-core.url https://bitbucket.org/fiviumuk/fivium-design-system-core.git
      - git submodule update --init --recursive

  - name: build-fds
    image: node:10
    commands:
      - cd fivium-design-system-core
      - npm install
      - npx gulp build
      - cd ..

  - name: build-frontend
    image: node:10
    commands:
      - npm install
      - npx gulp buildAll

  - name: build-java
    image: openjdk:11-jdk-slim
    environment:
      SONAR_TOKEN:
        from_secret: sonar_token
      GRADLE_USER_HOME: /drone/src/gradle_cache
      # This SONAR_USER_HOME is the cache path - not the actual user home
      SONAR_USER_HOME: /drone/src/sonar_cache
    commands:
      - chmod +x gradlew
      - ./gradlew test jacocoTestReport checkstyleMain bootWar bootJar sonarqube

  - name: publish-docker-develop
    image: plugins/docker:19.03.8
    settings:
      registry: quay.io
      repo: quay.io/fivium/pathfinder
      tags:
        - develop
      config:
        from_secret: docker_config
    when:
      branch:
        - develop
      status:
        - success

  - name: publish-docker
    image: plugins/docker:19.03.8
    settings:
      registry: quay.io
      repo: quay.io/fivium/pathfinder
      tags:
        - ${DRONE_BRANCH/\//-}-${DRONE_BUILD_NUMBER}
      config:
        from_secret: docker_config
    when:
      branch:
        - master
        - release/**
        - hotfix/**
        - publish-to-docker
        - rebrand-to-nsta
      status:
        - success

#  - name: vulnerability-scan-java
#    image: openjdk:11-jdk-slim
#    environment:
#      GRADLE_USER_HOME: /drone/src/gradle_cache
#    commands:
#      - chmod +x gradlew
#      - ./gradlew dependencyCheckAnalyze --stacktrace
#    volumes:
#      - name: nvd-db
#        path: /var/nvd-db
#    when:
#      branch: develop

  - name: vulnerability-scan-npm
    image: node:10.12.0
    commands:
      - npm audit > build/reports/npm-audit-report.txt || true # dont fail build if non 0 exit code
    when:
      branch: develop

  - name: sync-reports
    image: alpine:3.12.1
    commands:
      - mkdir -p /var/webfiles/${DRONE_BUILD_NUMBER}
      - cp -r build/reports /var/webfiles/${DRONE_BUILD_NUMBER}
    volumes:
      - name: webfiles
        path: /var/webfiles
    when:
      status: [ success, failure ]

  - name: deploy-dev-st
    image: plugins/downstream:linux-amd64
    settings:
      server: https://drone.fivium.co.uk
      token:
        from_secret: drone_token
      fork: true
      repositories:
        - fiviumuk/fivium-dev-app@master
    when:
      branch:
        - develop
      status:
        - success

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: drone-cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
        - ./gradle_cache
        - ./sonar_cache

  - name: slack
    image: plugins/slack:linux-amd64
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: oga-pathfinder
      template: |
        *{{build.status}}* <{{build.link}}|Commit {{truncate build.commit 7}} on {{build.branch}} by ${DRONE_COMMIT_AUTHOR_NAME}>
        Reports published to: http://drone-assets.fivium.local:9090/pathfinder/{{build.number}}/
    when:
      status: [ success, failure ]

volumes:
  - name: webfiles
    host:
      path: /home/fivium/www/pathfinder

  - name: nvd-db
    host:
      path: /home/fivium/nvd-db-pathfinder

  - name: drone-cache
    host:
      path: /home/fivium/drone-cache