package uk.co.ogauthority.pathfinder.auth;

public enum  UserPrivilege {
  PATHFINDER_WORK_AREA,
  PATHFINDER_REGULATOR_ADMIN,
  PATHFINDER_REG_ORG_MANAGER,
  PATHFINDER_ORG_ADMIN,
  PATHFINDER_PROJECT_CREATE,
  PATHFINDER_TEAM_VIEWER,
  PATHFINDER_PROJECT_VIEWER,
  PATHFINDER_PROJECT_ADMINISTRATOR,
  PATHFINDER_STATISTIC_VIEWER
}
