version: "3.8"
networks:
  app_net:
    external: true
    name: app_net

services:
  clamav:
    image: quay.io/fivium/clamav:76
    deploy:
      resources:
        limits:
          memory: 1536M
        reservations:
          memory: 1536M
    networks:
      - app_net

  pathfinder:
    image: pathfinder:develop
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8081/engedudev1/pathfinder/actuator/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 2
    deploy:
      mode: global
      update_config:
        parallelism: 2
        delay: 0s
        failure_action: rollback
        monitor: 90s
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 30s
      resources:
        limits:
          memory: 1536M
        reservations:
          memory: 1536M
    networks:
      - app_net
    ports:
      - 8081:8081
    environment:
      PATHFINDER_CONTEXT: "/engedudev1/pathfinder/"
      PATHFINDER_DB_URL: "edu-dev-db5.decc.local:1521:edudev1"
      PATHFINDER_DB_SCHEMA: "PATHFINDER"
      PATHFINDER_DB_PASSWORD: "dev1"
      PATHFINDER_FOX_LOGIN_URL: "http://edu-app3.decc.local/engedudev1/fox/nsta/NSTA_LOGIN/login?REFERRED_BY=PATHFINDER"
      PATHFINDER_FOX_LOGOUT_URL: "http://edu-app3.decc.local/engedudev1/fox/nsta/NSTA_LOGIN/logout"
      PATHFINDER_FOX_REGISTRATION_URL: "http://edu-app3.decc.local/engedudev1/fox?foxopen=nsta/LOGIN001L/register"
      PATHFINDER_ENABLE_STATSD: "false"
      PATHFINDER_CLAMAV_HOST: "clamav"
      PATHFINDER_CLAMAV_PORT: 3310
      PATHFINDER_CLAMAV_TIMEOUT: 60000